.github/workflows/push_master.yaml, sass/example/_exampleTool.sass, sass/parts/_overview.sass, sass/ui/_button.sass, sass/ui/_modal.sass, src/editor/api.ts, src/editor/editor.ts, src/editor/parts/content/toolbar.ts, src/editor/parts/overview.ts, src/editor/parts/preview/toolbar.ts, src/editor/state.ts, src/example/exampleApi.ts, src/example/exampleTool.ts, yarn.lock
Add ability in the api and the UI to 'publish' the workspace.
[Design Doc](https://docs.google.com/document/d/1e28z2a5EQD3aXYpw4F1fKOnAgvCyKLXliUblV4QZuQA/) for workflows.
=> Publish workflow

src/editor/api.ts, src/editor/parts/menu/site.ts, src/editor/state.ts, src/example/exampleApi.ts, src/utility/filter.test.ts, src/utility/filter.ts
Added ability to configure the site files list by providing a config for the include/exclude filter.
=> Include/exclude filter for filtering arrays.

src/editor/field/image.ts, src/mixin/listeners.test.ts, src/utility/math.test.ts, src/utility/math.ts, src/utility/storage.test.ts
Improve the code coverage for unit testable pieces of the editor.
=> Coverage improvements.

src/utility/deepClean.test.ts, src/utility/deepClean.ts, src/utility/storage.test.ts
Goal is to be able to clean up a data object based on a config of what things to clean out.
- Remove empty objects.
- Remove empty arrays.
- Remove empty strings.
- Remove undefined values.
- Remove null values.
=> Deep clean utility for cleaning up structured data.

sass/_config.sass, sass/parts/_menu.sass, sass/parts/content/_sectionHistory.sass, sass/ui/_list.sass, src/editor/api.ts, src/editor/parts/content.ts, src/editor/parts/content/sectionHistory.ts, src/editor/parts/overview.ts, src/editor/state.ts, src/example/example.ts, src/example/exampleApi.ts
Flesh out the file history in the api and in the content section for history.
=> File history display

package.json, sass/_config.sass, sass/editor.sass, sass/ui/_modal.sass, sass/ui/_toast.sass, src/editor/editor.ts, src/editor/events.ts, src/editor/parts/content/sectionHistory.ts, src/editor/parts/notifications.ts, src/editor/parts/overview.ts, src/editor/parts/toasts.ts, src/editor/ui/toast.ts, yarn.lock
Show a toast when adding notifications to let users know that a new notification has been added and allow for taking action easily.
=> Toasts for notifications

package.json, src/editor/field/aside.ts, src/example/example.ts, src/example/exampleApi.ts, src/example/field/exampleAside.ts, yarn.lock
Example 'pages' with an example aside for code samples.
Generic aside for displaying information apart from the normal help text from markdown.
=> Aside field for generic html output and example aside for example configs.

sass/parts/_content.sass, sass/parts/content/_sectionRaw.sass, src/editor/api.ts, src/editor/editor.ts, src/editor/events.ts, src/editor/parts/content/sectionFields.ts, src/editor/parts/content/sectionHistory.ts, src/editor/parts/content/sectionRaw.ts, src/editor/state.ts, src/example/exampleApi.ts
Ability to edit the raw content of a file.
Also added the api for saving a file.
=> Raw content editing

package.json, sass/selective/_field.sass, sass/selective/field/_media.sass, src/editor/editor.ts, src/editor/field/media.ts, src/example/example.ts, src/example/exampleApi.ts, src/example/field/exampleField.ts, yarn.lock
Updating the media field to add the label and extra fields.
=> Improvements to the media field.

src/server/api.ts
Adding push state for the content file being loaded.
=> Separating out the api url resolution from editor urls.

package.json, sass/selective/_field.sass, sass/selective/field/_grow_partials.sass, src/editor/api.ts, src/editor/editor.ts, src/editor/parts/menu/workspaces.ts, src/editor/state.ts, src/example/exampleApi.ts, src/projectType/grow/field/partials.ts, src/projectType/grow/growApi.ts, src/projectType/grow/growProjectType.ts, src/projectType/grow/growState.ts, yarn.lock
Partials field for grow that loads the partial configurations and displays the partials in a list.
=> Grow partials field

package.json, src/editor/autoFields.ts, src/editor/parts/content/section.ts, src/editor/parts/content/toolbar.ts, src/projectType/grow/field/partials.ts, yarn.lock
Improve the partial previews and use a custom auto fields class for guessing fields in the editor.
=> Fields content improvements.

src/utility/deepWalk.test.ts, src/utility/deepWalk.ts
Fixed a missing async await for results.
=> Add more customizability for walking records and arrays.

src/example/example.ts, src/example/exampleApi.ts, src/example/field/exampleField.ts, src/mixin/autocomplete.ts, src/projectType/amagaki/amagakiProjectType.ts, src/projectType/amagaki/field/static.ts, src/projectType/generic/field/constructor.ts, src/projectType/grow/field/document.ts, src/projectType/grow/field/static.ts, src/utility/prioritySort.test.ts, src/utility/prioritySort.ts
Polishing grow and amagaki constructor fields (ex: document, static file, string fields).
=> Grow and Amagaki Constructor Fields

src/remoteMedia/GCSRemoteMedia.ts, src/remoteMedia/index.ts, src/server/api.ts, src/server/editor.ts
Ability to easily add remote media providers instead of having to hard code them into the server api.
=> feat: Dynamic remote media providers for editor server.

README.md, gulpfile.js, package.json, sass/selective/_field.sass, sass/selective/field/_html.sass, sass/selective/field/_markdown.sass, src/editor/field/html.ts, src/editor/field/markdown.ts, src/editor/field/media.ts, src/example/example.ts, src/example/exampleApi.ts, src/example/field/exampleField.ts, src/server/editor.ts, src/server/server.ts, static/server/index.html, yarn.lock
Using quill and toastui editor for html and markdown fields.
No support for media upload yet.
=> feat: Html and Markdown Fields

src/sass/_config.sass, src/sass/_scheme.sass, src/sass/editor.sass, src/sass/parts/content/_header.sass, src/sass/selective/_field.sass, src/sass/selective/field/_list.sass, src/sass/ui/_button.sass, src/sass/ui/_list.sass, src/ts/editor/parts/content/footer.ts, src/ts/editor/parts/content/sectionRaw.ts, src/ts/example/exampleApi.ts
- Remove branding in footer
- Add a slight hover effect to repeated panels
- Fix a bug on the history page I caused earlier
Screenshot of the hover effect:
=> chore: incrementally clean up ui

src/sass/_config.sass, src/sass/_scheme.sass, src/sass/example/_exampleTool.sass, src/sass/parts/_menu.sass, src/sass/parts/_notifications.sass, src/sass/parts/content/_header.sass, src/sass/parts/preview/_frame.sass, src/sass/selective/_field.sass, src/sass/selective/field/_generic_partials.sass, src/sass/selective/field/_list.sass, src/sass/selective/field/_mediaList.sass, src/sass/selective/mixins/_autocomplete.sass, src/sass/selective/mixins/_options.sass, src/sass/server/_local.sass, src/sass/ui/_error.sass, src/sass/ui/_modal.sass
There were some colors that were not part of the scheme, this is now updated. Some generic choices were made for the dark colors, but they can be updated later to use better colors.
=> fix: move all colors into the scheme

src/sass/_config.sass, src/sass/_scheme.sass, src/sass/parts/preview/_frame.sass
Uses color scheme options for a gridded background in the preview area.
=> chore: grid background for preview area

src/sass/_scheme.sass, src/ts/editor/editor.ts, src/ts/editor/parts/content.ts, src/ts/editor/parts/content/footer.ts, src/ts/editor/state.ts
Ability to update the dark/light mode ui and override the preferred color scheme.
=> feat: dark/light mode toggle

src/sass/ui/_list.sass, src/ts/editor/editor.ts, src/ts/editor/parts/content.ts, src/ts/editor/parts/content/footer.ts, src/ts/editor/parts/empty.ts, src/ts/editor/parts/menu.ts, src/ts/editor/parts/menu/site.ts, src/ts/editor/parts/menu/users.ts, src/ts/editor/parts/menu/workspaces.ts, src/ts/editor/parts/overview.ts
Add a "Recent file" list for the 'empty' editor when loaded without a file path.
Also moves the scheme toggle to the menu.
=> feat: recent file list for the empty editor state.

src/ts/example/example.ts, src/ts/example/exampleApi.ts, src/ts/projectType/generic/field/partials.ts
=> fix: add partial not being passed correct state

package.json, src/sass/ui/_button.sass, src/ts/editor/parts/content/sectionFields.ts, src/ts/example/exampleApi.ts, yarn.lock
=> feat: auto guess fields when no editor config available

package.json, src/ts/editor/events.ts, src/ts/editor/parts/content.ts, src/ts/editor/parts/content/sectionFields.ts, src/ts/editor/parts/menu/workspaces.ts, src/ts/editor/parts/overview.ts, src/ts/editor/state.ts, src/ts/projectType/generic/field/partials.ts, yarn.lock
fix: refining how the selective fields are auto guessed.
=> fix: action for creating missing file

src/ts/projectType/amagaki/field/yaml.ts, src/ts/projectType/grow/field/yaml.ts
=> fix: adjust filter to not filter only content yaml files

package.json, src/sass/_config.sass, src/sass/selective/_field.sass, src/sass/selective/field/_generic_partials.sass, src/sass/selective/field/_list.sass, src/sass/ui/_button.sass, yarn.lock
Sending the review to @Zoramite -- check out the button style technique we've used on other projects. It places Material Icons in the button using the following approach:
```
content: var(--button-icon)
```
=> chore: cleanup button styles

src/ts/editor/state.ts
=> fix: reload preview server config after creating or copying file

package.json, src/sass/selective/field/_variant.sass, src/sass/ui/_button.sass, src/ts/example/exampleApi.ts, yarn.lock
Updates the variant field to remove the label and show an icon for clearing the selected variant.
fixes: #134
=> fix: style the variant for changes to the label and ability to clear

src/ts/editor/state.ts
=> feat: title updating with content changes

package.json, src/ts/editor/state.ts, src/ts/editor/ui/parts/dashboard.ts, src/ts/editor/ui/parts/onboarding/github.ts, yarn.lock
Local projects don't have an identifier that can keep churn between different repositories and branches.
=> fix: restrict history for local projects

package.json, src/ts/utility/filter.test.ts, src/ts/utility/filter.ts, webpack.common.js, yarn.lock
Useful for doing glob style pattern matching.
=> feat: Glob style filter.

src/sass/parts/_overview.sass, src/ts/editor/api.ts, src/ts/editor/ui/parts/menu.ts, src/ts/editor/ui/parts/overview.ts, src/ts/server/api.ts, src/ts/server/gh/githubApi.ts
Ability for the api to return a list of breadcrumb links for the UI to use.
This allows the UI to link to different levels of the project (ex: link to the onboarding flow) easily.
=> feat: Project breadcrumb links.

src/ts/projectType/amagaki/amagakiAutoFields.ts, src/ts/projectType/grow/growAutoFields.ts
=> fix: Project type specific guessing of partials.

src/ts/editor/editor.ts, src/ts/editor/ui/modal.ts, src/ts/editor/ui/parts/content/section.ts, src/ts/editor/ui/parts/menu/site.ts, src/ts/editor/ui/parts/menu/workspaces.ts, src/ts/editor/ui/parts/overview.ts, src/ts/projectType/generic/field/partials.ts
Also fixed the partials to only show the add button after the list of partials loads.
=> fix: Clone of selective config causes global objects to be cloned.

package.json, src/sass/editor.sass, src/sass/selective/_field.sass, src/sass/selective/_selective.sass, src/sass/selective/field/_unknown.sass, src/sass/ui/_info.sass, src/sass/ui/_warning.sass, src/ts/editor/field/html.ts, src/ts/editor/field/media.ts, src/ts/editor/field/mediaList.ts, src/ts/editor/field/unknown.ts, src/ts/editor/template.ts, src/ts/editor/ui/parts/content/sectionFields.ts, src/ts/example/exampleApi.ts, src/ts/projectType/generic/field/constructor.ts, yarn.lock
When the editor is trying to show a field but the value is not able to be used for the field it will show a message that the value is not editable in the editor UI.
When a field type is not recognized and `Unknown` field will be used that shows a message that the field type needs to be updated.
fixes #154
fixes #94
=> feat: Message when field values are invalid for field or missing field.

package.json, src/ts/editor/field/media.ts, src/ts/editor/ui/modal.ts, src/ts/editor/ui/parts/content/sectionFields.ts, src/ts/editor/ui/parts/content/sectionRaw.ts, src/ts/editor/ui/parts/menu/site.ts, src/ts/editor/ui/parts/menu/workspaces.ts, src/ts/editor/ui/parts/overview.ts, src/ts/projectType/generic/field/constructor.ts, src/ts/projectType/generic/field/partials.ts, yarn.lock
For a better user experience, wait to validate form fields until the user 'leaves' the field. This provides a more immediate feedback for the user on the value without distracting the user during input.
Also enables the form 'submit' and then marking all errors before disabling the button if invalid.
=> feat: Validation delay for forms and fields.

package.json, src/ts/editor/field/mediaList.ts, src/ts/editor/ui/parts/menu/site.ts, yarn.lock
Uses upstream fix for sortable to not allow dragging when there is a form input in focus.
=> fix: Sorting elements use updated focus handlers to not drag inputs.

src/ts/editor/ui/modal.ts, src/ts/editor/ui/parts/overview.ts
Since the forms are short on the modals delay the validation until the user tries to submit the form.
=> feat: Delay validation on form modal.

src/sass/parts/_notifications.sass, src/sass/parts/_overview.sass, src/sass/parts/onboarding/_toolbar.sass, src/ts/editor/api.ts, src/ts/editor/state.ts, src/ts/editor/ui/parts/onboarding/toolbar.ts, src/ts/editor/ui/parts/overview.ts, src/ts/example/exampleApi.ts, src/ts/server/api.ts, src/ts/server/gh/githubApi.ts, src/ts/server/gh/githubCallback.ts
Ability to log out of GitHub authenticated project and make the login work across tabs using local storage.
fixes #220
=> feat: GitHub authenticaion log out.

src/sass/_scheme.sass, src/sass/editor.sass, src/sass/ui/_list.sass
=> fix: Coloring for icons in the list to only target non-special leafs.

src/ts/editor/events.ts, src/ts/editor/state.ts, src/ts/editor/ui/parts/content/toolbar.ts, src/ts/projectType/amagaki/amagakiState.ts, src/ts/projectType/amagaki/field/partials.ts, src/ts/projectType/generic/field/partials.ts, src/ts/projectType/grow/field/partials.ts, src/ts/projectType/grow/growState.ts, src/ts/projectType/state.ts
Instead of needing to reload the entire page to check for changes it now reloads just the individual file and clears the partials.
=> feat: File refresh icon for reloading the file (and partials).

src/ts/editor/events.ts, src/ts/editor/ui/parts/preview/frame.ts, src/ts/editor/ui/parts/preview/toolbar.ts
Allows users to manually refresh the preview.
=> feat: Manual refresh for preview.

package.json, src/ts/editor/ui/app.ts, src/ts/projectType/generic/field/constructor.ts, src/ts/timeago-locale-en.json, yarn.lock
The constructor validation was not using the validation zones which was missing the value check since it was not using the `_data` portion of the constructor value.
=> fix: Constructor validation using the zones to correctly match value.

src/ts/editor/ui/parts/onboarding/github.ts
Instead of failing silently, show an error message when the workspace loading fails.
Fixes #176
=> fix: Show error message when requesting non-existent repository.
