blinkk/editor.dev-ui

- src/utility/deepClean.test.ts
- src/utility/deepClean.ts
This allows for protecting keys that would normally be cleaned up, such as protecting `$path@env.prod: ~` in the grow documents.
> Ability to protect certain keys from being cleaned.

- src/editor/api.ts
- src/editor/field/media.ts
- src/editor/field/mediaList.ts
- src/example/field/exampleField.ts
- src/index.ts
- src/server/editor.ts
Updated the media fields, removed the `remoteMedia` and `remoteMediaList`. Instead the media field will use the media settings from the editor config to figure out the default media options to use. Individual fields can now override the global default for remote media by providing a `remote` config for the field.
> feat!: Media field improvements

- package.json
- src/remoteMedia/GCSRemoteMedia.ts
- src/server/api.ts
- yarn.lock
Updated the media fields, removed the `remoteMedia` and `remoteMediaList`. Instead the media field will use the media settings from the editor config to figure out the default media options to use. Individual fields can now override the global default for remote media by providing a `remote` config for the field.
> fix: Upload file needs to use fetch until bent issue is fixed.

- src/ts/utility/stringLiteral.test.ts
- src/ts/utility/stringLiteral.ts
Used for when using values from the configuration file for creating values in the editor.
For example, being able to provide a preview url with a param for the workspace: `https://project-${workspace}.domain.com/`
> feat: ability to do arbitrary string literals

- src/sass/ui/_list.sass
- Use an `::after` element to fix the hover state of the list items.
- Also increases the click target area of the menu items (correctly!). Consistent with VSCode menu tree.
Fix is on the left:
> fix: fix issue with hover and selected list items

- src/sass/_config.sass
- src/sass/ui/_actions.sass
- src/sass/ui/_list.sass
- Make icon sizes in menu consistent
- Condense horizontal spacing to give more room for filenames
- Position actions absolutely to give filenames more room
- Remove red color of actions since it can conflict with themes, plus VSCode and Figma, etc. don't seem to use colors for icons inside app UI components
- Remove transition of actions (hover effects shouldn't transition for perf reasons)
Proposed (left) vs current (right)
> fix: condense menu

- src/ts/editor/field/media.ts
Not sure if this is the right fix but it guards against the crash.
Fixes this error:
```
Uncaught TypeError: e.path.startsWith is not a function
at u.get previewUrl [as previewUrl] (app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:50873)
at u.templatePreviewMedia (app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:50979)
at l.templateCollapsed (app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:51306)
at l.template (app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:51260)
at app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:51228
at app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:35794
at f.commit (app.min.js?fingerprint=2f9b7d317dbae006e7bc3da2a168810f:formatted:36134)
at o.update …
```
> fix: fix an issue when the media preview is not a string

- src/ts/editor/state.ts
When loading or saving a file, the url may not be known. Fix so that after both instances it attempts to load the url from the preview server.
fixes: #82
> fix: saving a file updates the url after save

- src/ts/editor/events.ts
- src/ts/editor/parts/preview/frame.ts
- src/ts/editor/state.ts
Add an event for after the file is saved. Listen for the event and refresh the iframe if it exists.
fixes #87
> fix: reload iframe after file save

- src/sass/ui/_actions.sass
- src/sass/ui/_list.sass
- src/ts/editor/parts/menu/site.ts
- src/ts/example/exampleApi.ts
Previously the actions were always there, but not shown and file names were truncated even when they didn't need to be.
> fix: only truncate file names on hover for file list

- src/ts/editor/parts/preview/toolbar.ts
- src/ts/editor/state.ts
- src/ts/example/exampleApi.ts
Adding promise callback handling to bind to the existing promise if there is already a promise in the works.
This prevents the callback from being lost when there is already a request in process.
Also fixed the example api to use a 'preview server' for the `/content/pages/index.yaml` in the example to simulate the process of using the api to load the preview server settings to determine the serving url of a page.
> fix: promise callback queue and example api for preview server

- src/ts/editor/state.ts
Fix up the way the State tracks the callbacks and uses a helper function to handle processing of the events around the data completion.
Also starts the loading of the preview server settings when the `getFile` is started instead of waiting for the `getFile` call to complete. (See: #97)
> refactor: state tracking of callbacks normalized

- src/ts/editor/editor.ts
- src/ts/editor/events.ts
- src/ts/editor/parts/content/section.ts
- src/ts/editor/parts/menu/site.ts
- src/ts/editor/parts/menu/workspaces.ts
- src/ts/editor/parts/overview.ts
- src/ts/editor/state.ts
- src/ts/editor/ui/modal.ts
- src/ts/projectType/amagaki/amagakiAutoFields.ts
- src/ts/projectType/amagaki/amagakiProjectType.ts
- src/ts/projectType/amagaki/field/document.ts
- src/ts/projectType/amagaki/field/static.ts
- src/ts/projectType/generic/field/partials.ts
- src/ts/projectType/grow/growAutoFields.ts
- src/ts/projectType/grow/growProjectType.ts
- src/ts/projectType/projectType.ts
Allows the project type to define custom auto guessing classes for use in guessing unknown fields.
Also moves the projectType variable from the Editor to the State.
fixes #95
> fix: auto field guessing for specific project types

- src/ts/editor/parts/dashboard.ts
- src/ts/editor/parts/preview.ts
- src/ts/editor/state.ts
- src/ts/server/api.ts
Update the preview to not prompt with the error if it cannot load the preview server config. Updated the message instead to show the message in the preview pane.
Fixes #106
> fix: missing preview config handled outside default handler

- src/ts/editor/state.ts
When changing the workspace, reload the files and the open file.
fixes: #111
> fix: reload files and file on workspace change

- src/sass/editor.sass
- src/sass/parts/_dashboard.sass
- src/ts/editor/parts/content.ts
- src/ts/editor/parts/dashboard.ts
- src/ts/editor/parts/menu.ts
- src/ts/editor/parts/overview.ts
- src/ts/editor/parts/preview.ts
Use the tertiary color as the background color to provide the gap coloring for panels.
Part of #143
> fix: border color between panels of UI

- src/sass/parts/_onboarding.sass
- src/ts/editor/api.ts
- src/ts/editor/recent.ts
- src/ts/editor/state.ts
- src/ts/editor/ui/parts/dashboard.ts
- src/ts/editor/ui/parts/onboarding/github.ts
Pulling the logic for a the editor history out of the dashboard UI and into a separate class that is part of the state.
> feat: editor history as a stand alone part of the state

- src/sass/parts/_preview.sass
- src/sass/ui/_button.sass
- src/ts/editor/api.ts
- src/ts/editor/ui/parts/preview.ts
- src/ts/editor/ui/parts/preview/toolbar.ts
Adds the ability to open the preview server's base url in a window and reloads the preview config either manually or after the 'login' window is closed to test if the request is able to proceed.
fixes #158
> fix: UX messaging around the preview status.

- src/sass/parts/_menu.sass
- src/sass/parts/content/_footer.sass
- src/sass/parts/menu/_footer.sass
- src/sass/parts/preview/_toolbar.sass
- src/sass/ui/_actions.sass
- src/sass/ui/_button.sass
- src/sass/ui/_modal.sass
- src/sass/ui/_tooltip.sass
- src/ts/editor/ui/parts/menu.ts
- src/ts/editor/ui/parts/menu/footer.ts
- src/ts/editor/ui/parts/preview/toolbar.ts
Move the light/dark mode into a menu footer.
Cleanup some of the styling with actions and disabled states.
> fix: Footer for the menu with light/dark mode toggle.

- src/ts/editor/state.ts
- src/ts/editor/ui/parts/dashboard.ts
- src/ts/editor/ui/parts/menu.ts
- src/ts/editor/ui/parts/menu/site.ts
- src/ts/editor/ui/parts/menu/users.ts
- src/ts/editor/ui/parts/menu/workspaces.ts
- src/ts/editor/ui/parts/onboarding/github.ts
- src/ts/editor/ui/parts/onboarding/local.ts
- src/ts/editor/ui/parts/overview.ts
- src/ts/projectType/amagaki/field/document.ts
- src/ts/projectType/amagaki/field/static.ts
- src/ts/projectType/amagaki/field/yaml.ts
- src/ts/projectType/grow/field/document.ts
- src/ts/projectType/grow/field/static.ts
- src/ts/projectType/grow/field/yaml.ts
When data is being retrieved from the api it handles the error and displays a notification, but the next render tries to reload the same api call since the value is still `undefined`.
This change gives a `null` value for data in the state for the values that are loaded without arguments and adds helper functions that trigger the api calls if the value is `undefined` but not if it is `null`. This makes it simpler for the UI to use the state without having to know and handle the `null` state and still allow for lazy loading of the data.
fixes #128
> fix: Infinite loading when errors retrieving data

- src/sass/ui/_list.sass
- src/ts/editor/field/media.ts
- src/ts/editor/preview.ts
- src/ts/editor/state.ts
- src/ts/editor/ui/parts/preview.ts
- src/ts/example/exampleApi.ts
Since the preview server configuration has been implemented, allow the media field to look up the preview serving url from the preview server.
fixes #228
> feat: Media preview serving path from the preview server setting.

- src/ts/editor/api.ts
- src/ts/example/exampleApi.ts
- src/ts/projectType/generic/field/partials.ts
Allows the partial to be hidden from the partial list (ex: when adding a new partial to a page).
Also adds a priority option to be able to give priority to specific partials. For example, making the spacer partial appear first in the list.
Fixes #222
> feat: Hidden partials and partial priority.

- src/ts/editor/state.ts
- src/ts/editor/ui/parts/content.ts
- src/ts/editor/ui/parts/content/toolbar.ts
- src/ts/editor/ui/parts/preview.ts
Keeps the UI for the existing file while waiting for the next file to load.
Also hides the existing editing UI and show the loading UI instead when there is a loading file.
> fix: Keep existing preview state while loading a new file.

- src/ts/editor/ui/parts/menu/site.ts
Since there are no inputs it will always be clean.
> fix: Allow delete modal to submit when the form is clean.
